// <auto-generated />
namespace OopRestaurant201710.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTablesdatabasetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTablesdatabasetable));
        
        string IMigrationMetadata.Id
        {
            get { return "201710241137182_add Tables database table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
